- name: Create deployment user
  user: name={{user_name}} comment="Application deployment user"

- authorized_key: user={{user_name}} key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: Create deployment directory
  file: path={{deploy_directory}} owner={{user_name}} group="www-data" state=directory

- name: Make shared directories
  file: path={{deploy_directory}}/shared/{{item}} group="www-data" owner={{user_name}} state=directory
  with_items:
    - tmp
    - log
    - public
    - bundle
    - bin
    - config
    - config/puma
  tags: shared
