---
- name: add ppa
  apt_repository: repo='ppa:brightbox/ruby-ng'

- name: Install ruby
  apt: pkg=ruby2.1 update_cache=yes state=latest

- name: Install ruby dev
  apt: pkg=ruby2.1-dev update_cache=yes state=latest

- name: Install bundler
  gem: name=bundler state=latest user_install=no

- name: Install compass
  gem: name=compass state=latest user_install=no